travis:
  secure:
    BINSTAR_TOKEN: eIzn5BPqdVGkRpQ/OeCRVNtpY/Tdf53vsl1Ls36cNw5zlmptSBPRwFp5UgtkxX7nRCBXsVO6RyFWkl1jfx+brrsi4I1WcJ8KjZTGd8EUvJpcmEyKtdF3flYRxuuopq65LN67qkFYXfYBvkAa3x4cUHy76ImX6EmEcJf7yPNK2gLwJ3nlXi9FqQznwOzKXYVoLDF18RFfSRtV4kjwZQ3fzM5+EU5aPfsM5INsrabqBLub5x88wxkZigJlj3vOvvFeEQDQUeu5xBTe02FSyZmAIzG1uvU+YFSqE+bTNbIIcs542P47Zbpm2ulQGXK6XeUdg9NrAG2YY6gaAfalxvrghwzbsAn+S2zdOeVsJa9Npi4KzWUBWXBNN+9utXIfORVB8QbHW5LnDshjr9jCdSgXQP/viPAHIkiXAKphs7izpRCu2c25XCITcujHiPXFCIVtI92I3/bXVi+OIyWip3y6WWAyqDEpcXFHZVMP55i4WB+YBZicxsPNTbOgkchAxkFVad/wHYM9JnbNsYpewTqsrWCES0IRz/cco6R/uayYwBm7fmCId10ON1yOisQo7tWPhILB7V0TiNeb7PbZay/0QVmTaTJJvn3Mo1YsJ0OJRJFoMNVwD5ScRgXB11rIk16xr7glc10MKtNdrKKby1V+YRZRm0nQaPimasSQGyLIMMA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
